export const indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry"
];

export const cityStateData  = [
  { city: "Mumbai", state: "Maharashtra" },
  { city: "Delhi", state: "National Capital Territory of Delhi" },
  { city: "Chennai", state: "Tamil Nadu" },
  { city: "Bengaluru", state: "Karnataka" },
  { city: "Hyderabad", state: "Telangana" },
  { city: "Kolkata", state: "West Bengal" },
  { city: "Ahmedabad", state: "Gujarat" },
  { city: "Pune", state: "Maharashtra" },
  { city: "Nagpur", state: "Maharashtra" },
  { city: "Surat", state: "Gujarat" },
  { city: "Jaipur", state: "Rajasthan" },
  { city: "Lucknow", state: "Uttar Pradesh" },
  { city: "Kanpur", state: "Uttar Pradesh" },
  { city: "Indore", state: "Madhya Pradesh" },
  { city: "Bhopal", state: "Madhya Pradesh" },
  { city: "Ludhiana", state: "Punjab" },
  { city: "Patna", state: "Bihar" },
  { city: "Vadodara", state: "Gujarat" },
  { city: "Coimbatore", state: "Tamil Nadu" },
  { city: "Visakhapatnam", state: "Andhra Pradesh" },
  { city: "Rajkot", state: "Gujarat" },
  { city: "Nashik", state: "Maharashtra" },
  { city: "Aurangabad", state: "Maharashtra" },
  { city: "Madurai", state: "Tamil Nadu" },
  { city: "Jamshedpur", state: "Jharkhand" },
  { city: "Agra", state: "Uttar Pradesh" },
  { city: "Meerut", state: "Uttar Pradesh" },
  { city: "Faridabad", state: "Haryana" },
  { city: "Ghaziabad", state: "Uttar Pradesh" },
  { city: "Thane", state: "Maharashtra" },
  { city: "Vijayawada", state: "Andhra Pradesh" },
  { city: "Guwahati", state: "Assam" },
  { city: "Chandigarh", state: "Chandigarh" },
  { city: "Mysuru", state: "Karnataka" },
  { city: "Trichy (Tiruchirappalli)", state: "Tamil Nadu" },
  { city: "Salem", state: "Tamil Nadu" },
  { city: "Hubli", state: "Karnataka" },
  { city: "Tiruppur", state: "Tamil Nadu" },
  { city: "Durgapur", state: "West Bengal" },
  { city: "Ranchi", state: "Jharkhand" },
  { city: "Bhubaneswar", state: "Odisha" },
  { city: "Gwalior", state: "Madhya Pradesh" },
  { city: "Jodhpur", state: "Rajasthan" },
  { city: "Kochi", state: "Kerala" },
  { city: "Amritsar", state: "Punjab" },
  { city: "Rajpura", state: "Punjab" },
  { city: "Patiala", state: "Punjab" },
  { city: "Mohali", state: "Punjab" },
  { city: "Nawashar", state: "Punjab" },
  { city: "Bathinda", state: "Punjab" },
  { city: "Pathankot", state: "Punjab" },
  { city: "Allahabad (Prayagraj)", state: "Uttar Pradesh" },
  { city: "Varanasi", state: "Uttar Pradesh" },
  { city: "Raipur", state: "Chhattisgarh" },
  { city: "Kozhikode", state: "Kerala" },
  { city: "Mangalore", state: "Karnataka" },
  { city: "Jabalpur", state: "Madhya Pradesh" },
  { city: "Udaipur", state: "Rajasthan" },
  { city: "Solapur", state: "Maharashtra" },
  { city: "Guntur", state: "Andhra Pradesh" },
  { city: "Jalandhar", state: "Punjab" },
  { city: "Kota", state: "Rajasthan" },
  { city: "Gorakhpur", state: "Uttar Pradesh" },
  { city: "Bareilly", state: "Uttar Pradesh" },
  { city: "Aligarh", state: "Uttar Pradesh" },
  { city: "Moradabad", state: "Uttar Pradesh" },
  { city: "Bhiwandi", state: "Maharashtra" },
  { city: "Siliguri", state: "West Bengal" },
  { city: "Jammu", state: "Jammu and Kashmir" },
  { city: "Panipat", state: "Haryana" },
  { city: "Rohtak", state: "Haryana" },
  { city: "Sonipat", state: "Haryana" },
  { city: "Hisar", state: "Haryana" },
  { city: "Ambala", state: "Haryana" },
  { city: "Muzaffarnagar", state: "Uttar Pradesh" },
  { city: "Saharanpur", state: "Uttar Pradesh" },
  { city: "Noida", state: "Uttar Pradesh" },
  { city: "Greater Noida", state: "Uttar Pradesh" },
  { city: "Ghaziabad", state: "Uttar Pradesh" },
  { city: "Mathura", state: "Uttar Pradesh" },
  { city: "Rampur", state: "Uttar Pradesh" },
  { city: "Gurgaon", state: "Haryana" },
  { city: "Bhiwani", state: "Haryana" },
  { city: "Rewari", state: "Haryana" },
  { city: "Palwal", state: "Haryana" },
  { city: "Karnal", state: "Haryana" },
  { city: "Yamunanagar", state: "Haryana" },
  { city: "Kurukshetra", state: "Haryana" },
  { city: "Kaithal", state: "Haryana" },
  { city: "Shimla", state: "Himachal Pradesh" },
  { city: "Dehradun", state: "Uttarakhand" },
  { city: "Haridwar", state: "Uttarakhand" },
  { city: "Rishikesh", state: "Uttarakhand" },
  { city: "Haldwani", state: "Uttarakhand" },
  { city: "Rudrapur", state: "Uttarakhand" },
  { city: "Roorkee", state: "Uttarakhand" },
  { city: "Nainital", state: "Uttarakhand" },
  { city: "Almora", state: "Uttarakhand" },
  { city: "Pithoragarh", state: "Uttarakhand" },
  { city: "Kashipur", state: "Uttarakhand" },
  { city: "Srinagar", state: "Uttarakhand" },
  { city: "Tehri", state: "Uttarakhand" },
  { city: "Mussoorie", state: "Uttarakhand" },
  { city: "Pauri", state: "Uttarakhand" },
  { city: "Kotdwar", state: "Uttarakhand" },
  { city: "Bageshwar", state: "Uttarakhand" },
  { city: "Champawat", state: "Uttarakhand" },
  { city: "Lansdowne", state: "Uttarakhand" },
  { city: "Joshimath", state: "Uttarakhand" },
  { city: "Gopeshwar", state: "Uttarakhand" },
  { city: "Uttarkashi", state: "Uttarakhand" },
  { city: "Badrinath", state: "Uttarakhand" },
  { city: "Kedarnath", state: "Uttarakhand" },
  { city: "Gangotri", state: "Uttarakhand" },
  { city: "Yamunotri", state: "Uttarakhand" },
  { city: "Ranikhet", state: "Uttarakhand" },
  { city: "Mukteshwar", state: "Uttarakhand" },
  { city: "Chamba", state: "Uttarakhand" },
  { city: "New Tehri", state: "Uttarakhand" },
  { city: "Devprayag", state: "Uttarakhand" },
  { city: "Rudraprayag", state: "Uttarakhand" },
  { city: "Karnaprayag", state: "Uttarakhand" },
  { city: "Nandaprayag", state: "Uttarakhand" },
  { city: "Vishnuprayag", state: "Uttarakhand" },
  { city: "Gairsain", state: "Uttarakhand" },
  { city: "Dwarahat", state: "Uttarakhand" },
  { city: "Kichha", state: "Uttarakhand" },
  { city: "Bhuntar", state: "Himachal Pradesh" },
  { city: "Mandi", state: "Himachal Pradesh" },
  { city: "Kullu", state: "Himachal Pradesh" },
  { city: "Manali", state: "Himachal Pradesh" },
  { city: "Solan", state: "Himachal Pradesh" },
  { city: "Dharamsala", state: "Himachal Pradesh" },
  { city: "Chamba", state: "Himachal Pradesh" },
  { city: "Bilaspur", state: "Himachal Pradesh" },
  { city: "Kangra", state: "Himachal Pradesh" },
  { city: "Una", state: "Himachal Pradesh" },
  { city: "Hamirpur", state: "Himachal Pradesh" },
  { city: "Palampur", state: "Himachal Pradesh" },
  { city: "Nahan", state: "Himachal Pradesh" },
  { city: "Paonta Sahib", state: "Himachal Pradesh" },
  { city: "Dalhousie", state: "Himachal Pradesh" },
  { city: "Shimla", state: "Himachal Pradesh" },
  { city: "Kasauli", state: "Himachal Pradesh" }
];